Meant-Peru/chambeaya-front

src/components/shared/styled.tsx, src/pages/detailPost.tsx
=> modal aplicar

src/components/shared/footer.tsx, src/pages/login.tsx, src/pages/registerPostulant.tsx
=> CH-13-correciones gramaticales

src/pages/registerPostulant.tsx
=> CH-7-se-agrego-tipo-documento-carnet-extranjeria

src/pages/login.tsx, src/pages/registerPostulant.tsx
=> Ch 9 correcion gramatical en login

src/components/shared/footer.tsx, src/pages/login.tsx, src/pages/registerPostulant.tsx
=> Ch 11 correcion gramatical

src/pages/login.tsx
Before: 
After:
----
Before:
After:
Redirecciona a Registrar usuario
=> CH-16-CAMBIOS

src/components/CtaSection.tsx, src/components/hero.tsx, src/pages/login.tsx
=> CH-17-cambios-registrarme

src/components/CtaSection.tsx, src/components/hero.tsx, src/components/shared/footer.tsx, src/pages/login.tsx
=> CH-20-CAMBIO-FOOTER

src/components/CtaSection.tsx, src/components/hero.tsx, src/components/shared/footer.tsx, src/pages/login.tsx
=> CH-22-cambio-gramatica-cbo

public/index.html
=> Ch24-codigos-externos

src/pages/addJob.tsx, src/pages/bussiness.tsx, src/pages/register.tsx, src/pages/registerPostulant.tsx
Validación de campos
Usuario Postulante
Usuario empresa.
Usuario agente de ventas
=> Validation form

src/components/shared/header.tsx
He quitado contacto menu item del menú ya que no es necesario está página
=> #45: Remove contact link

src/pages/dahsboard.tsx
=> #88 como admi : en especialidad se actualizó el texto del modal 

src/components/MyApply.tsx, src/components/shared/header.tsx, src/hooks/useAuth.tsx, src/pages/DetailPostPostulant.tsx, src/pages/addJob.tsx, src/pages/myaccount.tsx, src/routers/AppRouter.tsx
Se añadio un loader escrito "Consultando tus postulaciones" que aparece desde que ingresas a la pestaña "Mis postulaciones" y durante la llamada a la api.
Luego muestra el resultado, si hay postulaciones se muestran las tarjetas, sino, se muestra el mensaje de "No hay postulaciones"
=> #32 Como postulante :  se cambio el mensaje si no hay postulaciones

src/components/MyApply.tsx, src/components/shared/header.tsx, src/hooks/useAuth.tsx, src/pages/DetailPostPostulant.tsx, src/pages/addJob.tsx, src/pages/myaccount.tsx, src/routers/AppRouter.tsx
*** Tomar en cuenta que ahora la ruta de myaccount lleva una subruta:
Antes:
`<Route path="myaccount" element={<MyAccount />} />`
Ahora:
`<Route path="myaccount/:id" element={<MyAccount />} />`
donde `id` es el número de orden del tab que se mostrara en la página de Mi Cuenta/Mi Perfil
.
=> #37 Se añadio una ruta dinamica para navegar por los tabs y poder acceder a mis publicaciones

src/components/MyApply.tsx, src/components/shared/atom/tag.tsx, src/components/shared/header.tsx, src/hooks/useAuth.tsx, src/pages/DetailPostPostulant.tsx, src/pages/addJob.tsx, src/pages/myaccount.tsx, src/routers/AppRouter.tsx
#35 
En el issue se detallo los siguientes pasos que se pueden hacer en base al pr con el componente.
=> #35 Se añadio la x en los tags

src/enviroment/enviroment.ts, src/hooks/usePostCompany.tsx, src/pages/DetailPostCompanys.tsx, src/util/job.service.ts
**** queda la observacion de que sucedera si no tiene postulaciones el post
=> como empresa ya es visible el detalle de las postulaciones

src/enviroment/enviroment.ts, src/hooks/useAuth.tsx, src/pages/myaccount.tsx, src/pages/registerPostulant.tsx
github.com/Meant-Peru/chambeaya_backend/issues/3
No puedo citar el issue de back, coloque notas en la tarea
=> se actualizo la integracion de updateUser

src/components/MyApply.tsx, src/components/shared/styled.tsx, src/hooks/usePosition.ts, src/hooks/useSkill.tsx, src/interfaces/DetailProjectInteface.ts, src/interfaces/Position.ts, src/interfaces/Skill.ts, src/pages/DetailProyecto.tsx, src/pages/accountSales.tsx, src/pages/addJob.tsx, src/pages/dahsboard.tsx, src/pages/listPosiciones.tsx, src/sass/pages/_dashboard.scss, src/sass/shared/_button.scss, src/util/company.service.ts, src/util/position.service.ts, src/util/skill.service.ts
=> editar posiciones skills

src/interfaces/DetailProjectInteface.ts, src/pages/DetailProyecto.tsx, src/sass/shared/_button.scss, src/util/company.service.ts
…para ambos servicios de subida de archivos
Notas en  #122
=> se implemento el  subir cronograma, se espera la validacion del back

src/components/ProjectsComponent.tsx, src/enviroment/enviroment.ts, src/hooks/usePostCompany.tsx, src/interfaces/DetailPostulant.ts, src/interfaces/DetailProjectInteface.ts, src/interfaces/DetailUserInterface.tsx, src/pages/DetailPostCompanys.tsx, src/pages/DetailPostPostulant.tsx, src/pages/DetailProyecto.tsx, src/util/job.service.ts
#96 Revisar las notas, el back debe hacer una correcion en el tipo de dato de los comprobantes.
=> Comprobantes de pago

src/components/ListCompany.tsx, src/components/MyApply.tsx, src/components/PostCompany.tsx, src/enviroment/enviroment.ts, src/interfaces/PostJob.ts, src/pages/DetailPostPostulant.tsx, src/pages/DetailProyecto.tsx, src/pages/DetailUser.tsx, src/pages/accountSales.tsx, src/pages/addJob.tsx, src/pages/register.tsx, src/pages/registerPostulant.tsx, src/routers/AppRouter.tsx, src/sass/main.scss, src/sass/pages/_dashboard.scss, src/sass/pages/_detailPost.scss, src/sass/pages/_detailPostCompany.scss, src/sass/pages/_detailProject.scss, src/sass/pages/_postJob.scss
y se encontro bugs de data de empresa en las publicaiones de trabajo
=> se coloco boton del detalle del post 

src/pages/registerPostulant.tsx
se quita la validacion del 3tab del registro de un postulante
#207
=> Fix : Error del registro postulante
